.PHONY: all clean
all: dissertation/dissertation.aux gas-adsorption/gas-ads.aux ising/ising-upload.tar.gz lj-cluster/lj-cluster.aux sad-2d/sad-2d.aux square-well/sq-well-upload.tar.gz

clean:
	rm -f "dissertation/dissertation.aux" "dissertation/dissertation.bbl" "dissertation/dissertation.blg" "dissertation/dissertation.idx" "dissertation/dissertation.loaf" "dissertation/dissertation.loap" "dissertation/dissertation.loat" "dissertation/dissertation.lof" "dissertation/dissertation.log" "dissertation/dissertation.lot" "dissertation/dissertation.out" "dissertation/dissertation.pdf" "dissertation/dissertation.toc" "gas-adsorption/figs/Combine_Figure.pdf" "gas-adsorption/figs/four-cases-pro.pdf" "gas-adsorption/figs/four-cases.pdf" "gas-adsorption/figs/hydrogen-298-gst.pdf" "gas-adsorption/figs/hydrogen-298-n-vs-G.pdf" "gas-adsorption/figs/hydrogen-298-rho-mu.pdf" "gas-adsorption/figs/hydrogen-77-gst.pdf" "gas-adsorption/figs/hydrogen-77-n-vs-G.pdf" "gas-adsorption/figs/hydrogen-77-rho-mu.pdf" "gas-adsorption/figs/methane-298-gst.pdf" "gas-adsorption/figs/methane-298-n-vs-G.pdf" "gas-adsorption/figs/methane-298-rho-mu.pdf" "gas-adsorption/figs/qst-vs-delta-G.pdf" "gas-adsorption/gas-ads.aux" "gas-adsorption/gas-ads.bbl" "gas-adsorption/gas-ads.blg" "gas-adsorption/gas-ads.log" "gas-adsorption/gas-ads.out" "gas-adsorption/gas-ads.pdf" "gas-adsorption/gas-adsNotes.bib" "ising/N128-Cv-error-default.pdf" "ising/N128-entropy-error-default.pdf" "ising/N32-Cv-error-default.pdf" "ising/N32-Cv.pdf" "ising/N32-entropy-error-default.pdf" "ising/gamma-n128.pdf" "ising/gamma-n32.pdf" "ising/ising-upload.tar.gz" "ising/ising.aux" "ising/ising.bbl" "ising/ising.blg" "ising/ising.log" "ising/ising.pdf" "ising/isingNotes.bib" "lj-cluster/lj-cluster.aux" "lj-cluster/lj-cluster.bbl" "lj-cluster/lj-cluster.blg" "lj-cluster/lj-cluster.log" "lj-cluster/lj-cluster.pdf" "lj-cluster/lj-clusterNotes.bib" "sad-2d/sad-2d.aux" "sad-2d/sad-2d.bbl" "sad-2d/sad-2d.blg" "sad-2d/sad-2d.log" "sad-2d/sad-2d.pdf" "sad-2d/sad-2dNotes.bib" "square-well/N50-lndos-comparison.pdf" "square-well/gamma-n256.pdf" "square-well/lj-cv-error.pdf" "square-well/lj-cv.pdf" "square-well/periodic-ww1_30-ff0_30-N50-gamma-and-entropy-error-default.pdf" "square-well/periodic-ww1_30-ff0_30-N50-gamma-and-entropy-error-slow.pdf" "square-well/periodic-ww1_50-ff0_17-N256-entropy-error-default.pdf" "square-well/sq-well-upload.tar.gz" "square-well/sq-well.aux" "square-well/sq-well.bbl" "square-well/sq-well.blg" "square-well/sq-well.log" "square-well/sq-well.pdf" "square-well/sq-wellNotes.bib"
dissertation/dissertation.aux dissertation/dissertation.bbl dissertation/dissertation.blg dissertation/dissertation.idx dissertation/dissertation.loaf dissertation/dissertation.loap dissertation/dissertation.loat dissertation/dissertation.lof dissertation/dissertation.log dissertation/dissertation.lot dissertation/dissertation.out dissertation/dissertation.pdf dissertation/dissertation.toc : dissertation/abstract.tex dissertation/acknowledgements.tex dissertation/beavtex.cls dissertation/conclusion.tex dissertation/contributors.tex dissertation/dissertation.tex dissertation/introduction.tex dissertation/thesis.bib gas-adsorption/figs/Combine_Figure.pdf gas-adsorption/figs/four-cases-pro.pdf gas-adsorption/figs/four-cases.pdf gas-adsorption/figs/g_st_simple.pdf gas-adsorption/figs/hkust-1_fancy.png gas-adsorption/figs/hydrogen-298-n-vs-G.pdf gas-adsorption/figs/hydrogen-77-n-vs-G.pdf gas-adsorption/figs/methane-298-gst.pdf gas-adsorption/figs/methane-298-n-vs-G.pdf gas-adsorption/figs/methane-298-rho-mu.pdf gas-adsorption/figs/qst-vs-delta-G.pdf gas-adsorption/gas-ads-appendix.tex gas-adsorption/gas-ads-body.tex ising/N128-Cv-error-default.pdf ising/N128-entropy-error-default.pdf ising/N32-Cv-error-default.pdf ising/N32-Cv.pdf ising/N32-entropy-error-default.pdf ising/gamma-n128.pdf ising/gamma-n32.pdf ising/ising-body.tex square-well/N50-lndos-comparison.pdf square-well/gamma-n256.pdf square-well/lj-cv-error.pdf square-well/lj-cv.pdf square-well/periodic-ww1_30-ff0_30-N50-gamma-and-entropy-error-default.pdf square-well/periodic-ww1_30-ff0_30-N50-gamma-and-entropy-error-slow.pdf square-well/periodic-ww1_50-ff0_17-N256-entropy-error-default.pdf square-well/sq-well-body.tex
	cd "dissertation" && pdflatex dissertation.tex && bibtex dissertation && pdflatex dissertation.tex && pdflatex dissertation.tex
gas-adsorption/figs/Combine_Figure.pdf : gas-adsorption/figs/Combine_Figure.svg
	cd "gas-adsorption" && inkscape --export-filename figs/Combine_Figure.pdf figs/Combine_Figure.svg || inkscape --export-pdf figs/Combine_Figure.pdf figs/Combine_Figure.svg
gas-adsorption/figs/four-cases-pro.pdf : gas-adsorption/figs/four-cases-pro.svg
	cd "gas-adsorption" && inkscape --export-filename figs/four-cases-pro.pdf figs/four-cases-pro.svg || inkscape --export-pdf figs/four-cases-pro.pdf figs/four-cases-pro.svg
gas-adsorption/figs/four-cases.pdf : gas-adsorption/figs/four-cases.svg
	cd "gas-adsorption" && inkscape --export-filename figs/four-cases.pdf figs/four-cases.svg || inkscape --export-pdf figs/four-cases.pdf figs/four-cases.svg
gas-adsorption/gas-ads.aux gas-adsorption/gas-ads.bbl gas-adsorption/gas-ads.blg gas-adsorption/gas-ads.log gas-adsorption/gas-ads.out gas-adsorption/gas-ads.pdf gas-adsorption/gas-adsNotes.bib : gas-adsorption/bibfile.bib gas-adsorption/figs/Combine_Figure.pdf gas-adsorption/figs/four-cases-pro.pdf gas-adsorption/figs/four-cases.pdf gas-adsorption/figs/g_st_simple.pdf gas-adsorption/figs/hkust-1_fancy.png gas-adsorption/figs/hydrogen-298-n-vs-G.pdf gas-adsorption/figs/hydrogen-77-n-vs-G.pdf gas-adsorption/figs/methane-298-gst.pdf gas-adsorption/figs/methane-298-n-vs-G.pdf gas-adsorption/figs/methane-298-rho-mu.pdf gas-adsorption/figs/qst-vs-delta-G.pdf gas-adsorption/gas-ads-appendix.tex gas-adsorption/gas-ads-body.tex gas-adsorption/gas-ads.tex
	cd "gas-adsorption" && pdflatex gas-ads.tex && bibtex gas-ads && pdflatex gas-ads.tex && pdflatex gas-ads.tex
gas-adsorption/figs/qst-vs-delta-G.pdf : gas-adsorption gas-adsorption/colors.py gas-adsorption/data/hydrogen-298.csv gas-adsorption/data/hydrogen-77.csv gas-adsorption/data/methane/AX21-298.txt gas-adsorption/data/methane/Co2dobdc-298.txt gas-adsorption/data/methane/HKUST1-298.txt gas-adsorption/data/methane/MOF5-298.txt gas-adsorption/data/methane/Mg2dobdc-298.txt gas-adsorption/data/methane/Ni2dobdc-298.txt gas-adsorption/data/methane/PCN14-298.txt gas-adsorption/data/methane-298.csv gas-adsorption/gibbs-qst.py
	cd "gas-adsorption" && python3 gibbs-qst.py noshow
gas-adsorption/figs/hydrogen-298-gst.pdf gas-adsorption/figs/hydrogen-298-n-vs-G.pdf gas-adsorption/figs/hydrogen-298-rho-mu.pdf : gas-adsorption gas-adsorption/colors.py gas-adsorption/data/hydrogen-298.csv gas-adsorption/data_scripts gas-adsorption/data_scripts/hydrogen.py gas-adsorption/isothermal-ads-gas-plot.py
	cd "gas-adsorption" && python3 isothermal-ads-gas-plot.py hydrogen 298 5 100 noshow
gas-adsorption/figs/hydrogen-77-gst.pdf gas-adsorption/figs/hydrogen-77-n-vs-G.pdf gas-adsorption/figs/hydrogen-77-rho-mu.pdf : gas-adsorption gas-adsorption/colors.py gas-adsorption/data/hydrogen-77.csv gas-adsorption/data_scripts gas-adsorption/data_scripts/hydrogen.py gas-adsorption/isothermal-ads-gas-plot.py
	cd "gas-adsorption" && python3 isothermal-ads-gas-plot.py hydrogen 77 5 100 noshow
gas-adsorption/figs/methane-298-gst.pdf gas-adsorption/figs/methane-298-n-vs-G.pdf gas-adsorption/figs/methane-298-rho-mu.pdf : gas-adsorption gas-adsorption/colors.py gas-adsorption/data/methane/AX21-298.txt gas-adsorption/data/methane/COF102-298.txt gas-adsorption/data/methane/Co2dobdc-298.txt gas-adsorption/data/methane/HKUST1-298.txt gas-adsorption/data/methane/MOF5-298.txt gas-adsorption/data/methane/Mg2dobdc-298.txt gas-adsorption/data/methane/Ni2dobdc-298.txt gas-adsorption/data/methane/PCN14-298.txt gas-adsorption/data/methane-298.csv gas-adsorption/data_scripts gas-adsorption/data_scripts/methane.py gas-adsorption/isothermal-ads-gas-plot.py
	cd "gas-adsorption" && python3 isothermal-ads-gas-plot.py methane 298 5.8 65 noshow
ising/ising.aux ising/ising.bbl ising/ising.blg ising/ising.log ising/ising.pdf ising/isingNotes.bib : ising/N128-Cv-error-default.pdf ising/N128-entropy-error-default.pdf ising/N32-Cv-error-default.pdf ising/N32-Cv.pdf ising/N32-entropy-error-default.pdf ising/gamma-n128.pdf ising/gamma-n32.pdf ising/ising-body.tex ising/ising.bib ising/ising.tex
	cd "ising" && pdflatex ising.tex && bibtex ising && pdflatex ising.tex && pdflatex ising.tex
ising/N128-Cv-error-default.pdf ising/N128-entropy-error-default.pdf : ising/data/comparison/N128-ising-sad-128/errors.txt ising/data/comparison/N128-ising-samc-1e7-128/errors.txt ising/data/comparison/N128-ising-samc-1e8-128/errors.txt ising/data/comparison/N128-ising-samc-1e9-128/errors.txt ising/data/comparison/N128-ising-wl-128/errors.txt ising/data/comparison/N128-ising-wl-128-minGamma/errors.txt ising/data/comparison/N128-ising-wl-128-minGamma-1e6/errors.txt ising/data/comparison/N128-ising-wl-inv-t-128/errors.txt scripts-python/colors.py scripts-python/comparison-plot.py
	cd "ising" && python3 ../scripts-python/comparison-plot.py 0 N128 default ising noshow
ising/N32-Cv-error-default.pdf ising/N32-entropy-error-default.pdf : ising/data/comparison/N32-ising-sad-32/errors.txt ising/data/comparison/N32-ising-samc-1e5-32/errors.txt ising/data/comparison/N32-ising-samc-1e6-32/errors.txt ising/data/comparison/N32-ising-samc-1e7-32/errors.txt ising/data/comparison/N32-ising-wl-32/errors.txt ising/data/comparison/N32-ising-wl-32-minGamma/errors.txt ising/data/comparison/N32-ising-wl-inv-t-32/errors.txt scripts-python/colors.py scripts-python/comparison-plot.py
	cd "ising" && python3 ../scripts-python/comparison-plot.py 0 N32 default ising noshow
ising/N32-Cv.pdf : ising/data/heat-capacity/N32-heat-capacity.csv scripts-python/colors.py scripts-python/ising-cv-plot.py scripts-python/readnew.py
	cd "ising" && python3 ../scripts-python/ising-cv-plot.py --file_dir=../ising/data/heat-capacity --N=32 --noshow
ising/gamma-n128.pdf : ising/data/gamma/n128/ising-sad-128.dat ising/data/gamma/n128/ising-wl-128-minGamma-1e6.txt ising/data/gamma/n128/ising-wl-128-minGamma.txt ising/data/gamma/n128/ising-wl-128.txt ising/data/gamma/n128/ising-wl-inv-t-128.txt scripts-python/colors.py scripts-python/ising-gamma-plot.py
	cd "ising" && python3 ../scripts-python/ising-gamma-plot.py n128 1.0 noshow
ising/gamma-n32.pdf scripts-python/__pycache__ : ising/data/gamma/n32/ising-sad-32.dat ising/data/gamma/n32/ising-wl-32-minGamma.txt ising/data/gamma/n32/ising-wl-32.txt ising/data/gamma/n32/ising-wl-inv-t-32.txt scripts-python/colors.py scripts-python/ising-gamma-plot.py
	cd "ising" && python3 ../scripts-python/ising-gamma-plot.py n32 1.0 noshow
ising/ising-upload.tar.gz : ising/N128-Cv-error-default.pdf ising/N32-Cv-error-default.pdf ising/N32-Cv.pdf ising/gamma-n128.pdf ising/gamma-n32.pdf ising/ising-body.tex ising/ising.bbl ising/ising.pdf ising/ising.tex
	cd "ising" && tar czvf ising-upload.tar.gz ising.tex ising-body.tex ising.bbl gamma-n32.pdf gamma-n128.pdf N32-Cv-error-default.pdf N128-Cv-error-default.pdf N32-Cv.pdf
lj-cluster/lj-cluster.aux lj-cluster/lj-cluster.bbl lj-cluster/lj-cluster.blg lj-cluster/lj-cluster.log lj-cluster/lj-cluster.pdf lj-cluster/lj-clusterNotes.bib : lj-cluster/lj-cluster.bib lj-cluster/lj-cluster.tex
	cd "lj-cluster" && pdflatex lj-cluster.tex && bibtex lj-cluster && pdflatex lj-cluster.tex && pdflatex lj-cluster.tex
sad-2d/sad-2d.aux sad-2d/sad-2d.bbl sad-2d/sad-2d.blg sad-2d/sad-2d.log sad-2d/sad-2d.pdf sad-2d/sad-2dNotes.bib : sad-2d/sad-2d.tex
	cd "sad-2d" && pdflatex sad-2d.tex && bibtex sad-2d && pdflatex sad-2d.tex && pdflatex sad-2d.tex
square-well/sq-well.aux square-well/sq-well.bbl square-well/sq-well.blg square-well/sq-well.log square-well/sq-well.pdf square-well/sq-wellNotes.bib : square-well/N50-lndos-comparison.pdf square-well/gamma-n256.pdf square-well/lj-cv-error.pdf square-well/lj-cv.pdf square-well/periodic-ww1_30-ff0_30-N50-gamma-and-entropy-error-default.pdf square-well/periodic-ww1_30-ff0_30-N50-gamma-and-entropy-error-slow.pdf square-well/periodic-ww1_50-ff0_17-N256-entropy-error-default.pdf square-well/sq-well-body.tex square-well/sq-well.bib square-well/sq-well.tex
	cd "square-well" && pdflatex sq-well.tex && bibtex sq-well && pdflatex sq-well.tex && pdflatex sq-well.tex
square-well/periodic-ww1_50-ff0_17-N256-entropy-error-default.pdf : scripts-python/colors.py scripts-python/comparison-plot.py square-well/data/comparison/s000/periodic-ww1.50-ff0.17-N256-sad-256/errors.txt square-well/data/comparison/s000/periodic-ww1.50-ff0.17-N256-samc-1e3-256/errors.txt square-well/data/comparison/s000/periodic-ww1.50-ff0.17-N256-samc-1e4-256/errors.txt square-well/data/comparison/s000/periodic-ww1.50-ff0.17-N256-samc-1e5-256/errors.txt square-well/data/comparison/s000/periodic-ww1.50-ff0.17-N256-samc-1e6-256/errors.txt square-well/data/comparison/s000/periodic-ww1.50-ff0.17-N256-wl-256/errors.txt square-well/data/comparison/s000/periodic-ww1.50-ff0.17-N256-wl-inv-t-256/errors.txt
	cd "square-well" && python3 ../scripts-python/comparison-plot.py 0 periodic-ww1.50-ff0.17-N256 default s000 noshow
square-well/N50-lndos-comparison.pdf : scripts-python/colors.py scripts-python/create-N50-lndos-comparison.py scripts-python/readnew.py square-well/data/samc-1e4-50-s1-reference-lndos.dat
	cd "square-well" && python3 ../scripts-python/create-N50-lndos-comparison.py
square-well/periodic-ww1_30-ff0_30-N50-gamma-and-entropy-error-default.pdf : scripts-python/colors.py scripts-python/gamma-and-entropy-plot.py square-well/data/comparison/s000/periodic-ww1.30-ff0.30-N50-sad-50/errors.txt square-well/data/comparison/s000/periodic-ww1.30-ff0.30-N50-samc-1e3-50/errors.txt square-well/data/comparison/s000/periodic-ww1.30-ff0.30-N50-samc-1e4-50/errors.txt square-well/data/comparison/s000/periodic-ww1.30-ff0.30-N50-samc-1e5-50/errors.txt square-well/data/comparison/s000/periodic-ww1.30-ff0.30-N50-samc-1e6-50/errors.txt square-well/data/comparison/s000/periodic-ww1.30-ff0.30-N50-wl-50/errors.txt square-well/data/comparison/s000/periodic-ww1.30-ff0.30-N50-wl-inv-t-50/errors.txt square-well/data/gamma/n50/sad-50.dat square-well/data/gamma/n50/wl-50.txt square-well/data/gamma/n50/wl-inv-t-50.txt
	cd "square-well" && python3 ../scripts-python/gamma-and-entropy-plot.py 0 s000/periodic-ww1.30-ff0.30-N50 default noshow
square-well/periodic-ww1_30-ff0_30-N50-gamma-and-entropy-error-slow.pdf : scripts-python/colors.py scripts-python/gamma-and-entropy-plot.py square-well/data/comparison/s000/periodic-ww1.30-ff0.30-N50-sad-50-slow/errors.txt square-well/data/comparison/s000/periodic-ww1.30-ff0.30-N50-samc-1e5-50-slow/errors.txt square-well/data/comparison/s000/periodic-ww1.30-ff0.30-N50-samc-1e6-50-slow/errors.txt square-well/data/comparison/s000/periodic-ww1.30-ff0.30-N50-samc-1e7-50-slow/errors.txt square-well/data/comparison/s000/periodic-ww1.30-ff0.30-N50-wl-50-slow/errors.txt square-well/data/comparison/s000/periodic-ww1.30-ff0.30-N50-wl-inv-t-50-slow/errors.txt square-well/data/gamma/n50/sad-50-slow.dat square-well/data/gamma/n50/wl-50-slow.txt square-well/data/gamma/n50/wl-inv-t-50-slow.txt
	cd "square-well" && python3 ../scripts-python/gamma-and-entropy-plot.py 0 s000/periodic-ww1.30-ff0.30-N50 slow noshow
square-well/gamma-n256.pdf : scripts-python/colors.py scripts-python/gamma-plot.py square-well/data/gamma/n256/sad-256.dat square-well/data/gamma/n256/wl-50.txt square-well/data/gamma/n256/wl-inv-t-256.txt
	cd "square-well" && python3 ../scripts-python/gamma-plot.py n256 1.0 noshow
square-well/lj-cv-error.pdf square-well/lj-cv.pdf : scripts-python/colors.py scripts-python/lj-31-comparison.py square-well/data/lj31/bench-cv.txt square-well/data/lj31/lj-inv-t-wl-31-bin0001-cv-error.txt square-well/data/lj31/lj-inv-t-wl-31-bin0005-cv-error.txt square-well/data/lj31/lj-inv-t-wl-31-bin001-52-cv-error.txt square-well/data/lj31/lj-inv-t-wl-31-bin001-52-cv.txt square-well/data/lj31/lj-inv-t-wl-31-bin001-52-wide-cv.txt square-well/data/lj31/lj-inv-t-wl-31-bin001-54-cv-error.txt square-well/data/lj31/lj-inv-t-wl-31-bin001-54-cv.txt square-well/data/lj31/lj-inv-t-wl-31-bin001-54-wide-cv.txt square-well/data/lj31/lj-inv-t-wl-31-bin001-58-cv-error.txt square-well/data/lj31/lj-inv-t-wl-31-bin001-58-cv.txt square-well/data/lj31/lj-inv-t-wl-31-bin001-cv-error.txt square-well/data/lj31/lj-inv-t-wl-31-bin001-cv.txt square-well/data/lj31/lj-inv-t-wl-31-bin001-wide-cv.txt square-well/data/lj31/lj-inv-t-wl-31-bin002-cv-error.txt square-well/data/lj31/lj-inv-t-wl-31-bin01-cv-error.txt square-well/data/lj31/lj-sad-31-bin0001-cv-error.txt square-well/data/lj31/lj-sad-31-bin001-cv-error.txt square-well/data/lj31/lj-sad-31-bin001-cv.txt square-well/data/lj31/lj-sad-31-bin001-wide-cv.txt square-well/data/lj31/lj-sad-31-bin002-cv-error.txt square-well/data/lj31/lj-sad-31-bin01-cv-error.txt square-well/data/lj31/lj-wl-31-bin0001-cv-error.txt square-well/data/lj31/lj-wl-31-bin0005-cv-error.txt square-well/data/lj31/lj-wl-31-bin001-cv-error.txt square-well/data/lj31/lj-wl-31-bin001-cv.txt square-well/data/lj31/lj-wl-31-bin001-wide-cv.txt square-well/data/lj31/lj-wl-31-bin002-cv-error.txt square-well/data/lj31/lj-wl-31-bin01-cv-error.txt square-well/data/lj31/wide-cv.txt
	cd "square-well" && python3 ../scripts-python/lj-31-comparison.py noshow
square-well/sq-well-upload.tar.gz : square-well/N50-lndos-comparison.pdf square-well/gamma-n256.pdf square-well/lj-cv-error.pdf square-well/lj-cv.pdf square-well/periodic-ww1_30-ff0_30-N50-gamma-and-entropy-error-default.pdf square-well/periodic-ww1_30-ff0_30-N50-gamma-and-entropy-error-slow.pdf square-well/periodic-ww1_50-ff0_17-N256-entropy-error-default.pdf square-well/sq-well-body.tex square-well/sq-well.bbl square-well/sq-well.pdf square-well/sq-well.tex
	cd "square-well" && tar czvf sq-well-upload.tar.gz sq-well.tex sq-well-body.tex sq-well.bbl N50-lndos-comparison.pdf gamma-n256.pdf periodic-ww1_30-ff0_30-N50-gamma-and-entropy-error-default.pdf periodic-ww1_30-ff0_30-N50-gamma-and-entropy-error-slow.pdf periodic-ww1_50-ff0_17-N256-entropy-error-default.pdf lj-cv.pdf lj-cv-error.pdf
