.PHONY: all clean
all: gas-adsorption/rsc-gas-ads-complete.aux

clean:
	rm -f "gas-adsorption/figs/Combine_Figure.pdf" "gas-adsorption/figs/four-cases-pro.pdf" "gas-adsorption/figs/four-cases.pdf" "gas-adsorption/figs/hydrogen-298-gst.pdf" "gas-adsorption/figs/hydrogen-298-n-vs-G.pdf" "gas-adsorption/figs/hydrogen-298-rho-mu.pdf" "gas-adsorption/figs/hydrogen-77-gst.pdf" "gas-adsorption/figs/hydrogen-77-n-vs-G.pdf" "gas-adsorption/figs/hydrogen-77-rho-mu.pdf" "gas-adsorption/figs/methane-298-gst.pdf" "gas-adsorption/figs/methane-298-n-vs-G.pdf" "gas-adsorption/figs/methane-298-rho-mu.pdf" "gas-adsorption/figs/qst-vs-delta-G.pdf" "gas-adsorption/rsc-gas-ads-complete.aux" "gas-adsorption/rsc-gas-ads-complete.bbl" "gas-adsorption/rsc-gas-ads-complete.blg" "gas-adsorption/rsc-gas-ads-complete.log" "gas-adsorption/rsc-gas-ads-complete.out" "gas-adsorption/rsc-gas-ads-complete.pdf"
gas-adsorption/figs/Combine_Figure.pdf : gas-adsorption/figs/Combine_Figure.svg
	cd "gas-adsorption" && inkscape --export-filename figs/Combine_Figure.pdf figs/Combine_Figure.svg || inkscape --export-pdf figs/Combine_Figure.pdf figs/Combine_Figure.svg
gas-adsorption/figs/four-cases-pro.pdf : gas-adsorption/figs/four-cases-pro.svg
	cd "gas-adsorption" && inkscape --export-filename figs/four-cases-pro.pdf figs/four-cases-pro.svg || inkscape --export-pdf figs/four-cases-pro.pdf figs/four-cases-pro.svg
gas-adsorption/figs/four-cases.pdf : gas-adsorption/figs/four-cases.svg
	cd "gas-adsorption" && inkscape --export-filename figs/four-cases.pdf figs/four-cases.svg || inkscape --export-pdf figs/four-cases.pdf figs/four-cases.svg
gas-adsorption/rsc-gas-ads-complete.aux gas-adsorption/rsc-gas-ads-complete.bbl gas-adsorption/rsc-gas-ads-complete.blg gas-adsorption/rsc-gas-ads-complete.log gas-adsorption/rsc-gas-ads-complete.out gas-adsorption/rsc-gas-ads-complete.pdf : gas-adsorption/bibfile.bib gas-adsorption/figs/Combine_Figure.pdf gas-adsorption/figs/four-cases-pro.pdf gas-adsorption/figs/four-cases.pdf gas-adsorption/figs/g_st_simple.pdf gas-adsorption/figs/hkust-1_fancy.png gas-adsorption/figs/hydrogen-298-n-vs-G.pdf gas-adsorption/figs/hydrogen-77-n-vs-G.pdf gas-adsorption/figs/methane-298-gst.pdf gas-adsorption/figs/methane-298-n-vs-G.pdf gas-adsorption/figs/methane-298-rho-mu.pdf gas-adsorption/figs/qst-vs-delta-G.pdf gas-adsorption/head_foot/DOI.pdf gas-adsorption/head_foot/LF.pdf gas-adsorption/head_foot/RF.pdf gas-adsorption/head_foot/RSC_LOGO_CMYK.pdf gas-adsorption/head_foot/dates.pdf gas-adsorption/head_foot/header_bar.pdf gas-adsorption/head_foot/journal_name.pdf gas-adsorption/rsc-gas-ads-complete.tex gas-adsorption/rsc.bst
	cd "gas-adsorption" && pdflatex rsc-gas-ads-complete.tex && pdflatex rsc-gas-ads-complete.tex && bibtex rsc-gas-ads-complete && pdflatex rsc-gas-ads-complete.tex && pdflatex rsc-gas-ads-complete.tex
gas-adsorption/figs/qst-vs-delta-G.pdf : gas-adsorption/colors.py gas-adsorption/data/hydrogen-298.csv gas-adsorption/data/hydrogen-77.csv gas-adsorption/data/methane/AX21-298.txt gas-adsorption/data/methane/Co2dobdc-298.txt gas-adsorption/data/methane/HKUST1-298.txt gas-adsorption/data/methane/MOF5-298.txt gas-adsorption/data/methane/Mg2dobdc-298.txt gas-adsorption/data/methane/Ni2dobdc-298.txt gas-adsorption/data/methane/PCN14-298.txt gas-adsorption/data/methane-298.csv gas-adsorption/gibbs-qst.py
	cd "gas-adsorption" && python3 gibbs-qst.py noshow
gas-adsorption/figs/hydrogen-298-gst.pdf gas-adsorption/figs/hydrogen-298-n-vs-G.pdf gas-adsorption/figs/hydrogen-298-rho-mu.pdf : gas-adsorption/colors.py gas-adsorption/data/hydrogen-298.csv gas-adsorption/data_scripts/hydrogen.py gas-adsorption/isothermal-ads-gas-plot.py
	cd "gas-adsorption" && python3 isothermal-ads-gas-plot.py hydrogen 298 5 100 noshow
gas-adsorption/figs/hydrogen-77-gst.pdf gas-adsorption/figs/hydrogen-77-n-vs-G.pdf gas-adsorption/figs/hydrogen-77-rho-mu.pdf : gas-adsorption/colors.py gas-adsorption/data/hydrogen-77.csv gas-adsorption/data_scripts/hydrogen.py gas-adsorption/isothermal-ads-gas-plot.py
	cd "gas-adsorption" && python3 isothermal-ads-gas-plot.py hydrogen 77 5 100 noshow
gas-adsorption/figs/methane-298-gst.pdf gas-adsorption/figs/methane-298-n-vs-G.pdf gas-adsorption/figs/methane-298-rho-mu.pdf : gas-adsorption/colors.py gas-adsorption/data/methane/AX21-298.txt gas-adsorption/data/methane/COF102-298.txt gas-adsorption/data/methane/Co2dobdc-298.txt gas-adsorption/data/methane/HKUST1-298.txt gas-adsorption/data/methane/MOF5-298.txt gas-adsorption/data/methane/Mg2dobdc-298.txt gas-adsorption/data/methane/Ni2dobdc-298.txt gas-adsorption/data/methane/PCN14-298.txt gas-adsorption/data/methane-298.csv gas-adsorption/data_scripts/methane.py gas-adsorption/isothermal-ads-gas-plot.py
	cd "gas-adsorption" && python3 isothermal-ads-gas-plot.py methane 298 5.8 65 noshow
